Aws setup
snaplapse/snaplapse pull request #7
Opened 2022-07-02 19:42 UTC by danielkim10

Not too much going on here, hopefully Monday's standup will clear up issues regarding the file structure of each service.

Also since setting up a user gives us 12 free months of free tier, we can probably use what's offered there to complete the rest of the project. I doubt we'll have to use the paid tiers, even though we did the analysis in the report.

2022-07-02 20:20 UTC, kcchik commented
deleted `db.sqlite3`

2022-07-02 20:20 UTC, kcchik approved these changes

2022-07-02 20:30 UTC, kcchik requested changes
there should be a `Pipfile` and `Pipfile.lock` to commit
i think the problem might be that u installed boto3 inside the shell
libraries only write to `Pipfile` and `Pipfile.lock` when done from outside the shell via pipenv install

2022-07-02 20:47 UTC, danielkim10 commented
> there should be a `Pipfile` and `Pipfile.lock` to commit i think the problem might be that u installed boto3 inside the shell libraries only write to `Pipfile` and `Pipfile.lock` when done from outside the shell via pipenv install

good catch, thanks

2022-07-03 02:13 UTC, kcchik approved these changes

2022-07-03 02:32 UTC, merged